server:
  port: 8081


spring:
  main:
    web-application-type: servlet

  datasource:
    url: jdbc:mysql://localhost:3306/web?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  session:
    store-type: none

mybatis:
  type-aliases-package: cn.edu.whut.sept.zuul.Entity
  mapper-locations: classpath:/Mysql/*.xml


